site_name: OSM Workshop
site_description: "Deze site bevat materiaal voor een OpenStreetMap Workshop"
site_author: Just van den Broecke Casper Kersten
copyright: "&copy; 2023 osgeo.nl"
site_url: https://osmws.osgeo.nl
repo_url: https://github.com/osgeonl/osmws.osgeo.nl
edit_uri: '/docs/src'
docs_dir: src
nav:
    - Thuis: index.md
#    - Intro:
#        - Specification: design/spec.md
#        - Architecture: design/architecture.md
#        - Data: design/data.md
#        - Deployment: design/gitops.md

use_directory_urls: true

theme:
    name: material
    palette:
        # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
        # Default is indigo (blue)
        scheme: default
        primary: green
    features:
        - navigation.sections
    favicon: assets/favicon.ico
    logo: assets/images/osmnl-logo.png

plugins:
    - search
    - mkdocs-video
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - skip-lightbox
        auto_caption: false
        caption_position: bottom

markdown_extensions:
    - meta # option to add some meta tags on top, title, author, date, etc
    - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
    - pymdownx.details # advanced collapsible panels
    - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
    - footnotes # notes bottom of page
    - attr_list # used to size images
    - md_in_html # used to size images

extra_css:
    # light and dark variations from material.io
    # https://material.io/resources/color/#!/?view.left=0&view.right=1
    - assets/stylesheets/termynal.css
    - assets/stylesheets/custom.css

extra_javascript:
    - assets/javascripts/termynal.js
    - assets/javascripts/custom.js
